Filter ship
marko2606/stena-react-native pull request #11
Opened 2017-06-16 11:46 UTC by NemanjaManot

2017-06-19 07:33 UTC, marijarahman requested changes

2017-06-19 07:33 UTC, marijarahman commented on src/actions/types.js
> +export const GET_DATA_ERROR = 'GET_DATA_ERROR';
We agreed to use something more descriptive like SHIP_GET_DATA

2017-06-19 07:33 UTC, marijarahman commented on src/components/FiltersShip/FiltersList.js
> +import { filterGroup2 } from '../../utils/FilterDropdownGroup';
Could you name this differently? FilterGroupHelper maybe

2017-06-19 07:33 UTC, marijarahman commented on src/components/FiltersShip/FiltersList.js
> +        }
i think switch loop looks cleaner in this case

2017-06-19 07:33 UTC, marijarahman commented on src/components/FiltersShip/FiltersList.js
> +            return this.state.activeFilterGroup4 ? arrowUp : arrowDown
also :)

2017-06-19 07:33 UTC, marijarahman commented on src/components/FiltersShip/FiltersList.js
> +
Unnecessary space

2017-06-19 07:33 UTC, marijarahman commented on src/components/FiltersShip/FiltersList.js
> +        if (!this.state.fontLoaded) {
You could write this in one line

2017-06-19 07:33 UTC, marijarahman commented on src/components/FiltersShip/FooterFiltersShip.js
> +                        <Ionicons name="ios-funnel" size={20} style={styles.footerIconWarning} />
Desctructure

2017-06-19 07:33 UTC, marijarahman commented on src/Router.js
> +import { FiltersShip } from './components/FiltersShip/FiltersShip';
I think you should rename "Ship" to "Vessel"

2017-06-20 11:55 UTC, marko2606 commented on src/Router.js
> +                        leftIcon="keyboard_arrow_down"  // TODO - arrow-left
I have already added arrow-left on GlobalMap component, when I merge it to dev you can use it too. :)

2017-06-20 12:07 UTC, marko2606 commented on src/components/FiltersVessel/FiltersList.js
> +        }
can you name this a little bit different? Maybe something like vesselTypeGroup, companyGroup...

2017-06-20 12:09 UTC, marko2606 commented on src/components/FiltersVessel/FiltersList.js
> +        switch (groups) {
refactor

2017-06-20 12:10 UTC, marko2606 commented on src/components/FiltersVessel/FiltersList.js
> +        let arrowUp = <Icon name="keyboard_arrow_up" size={25} color={colors['grayColor']}/>;
refactor

2017-06-20 12:12 UTC, marko2606 commented on src/components/FiltersVessel/FiltersVessel.js
> +import FooterFiltersShip from './FiltersVesselFooter';
different name from imported

2017-06-20 12:14 UTC, marko2606 commented on src/components/FiltersVessel/FiltersVesselFooter.js
> +            <Footer>
refactor

2017-06-20 12:59 UTC, marijarahman commented on src/Router.js
> +import { FiltersShip } from './components/FiltersVessel/FiltersVessel';
Vessel? :)

2017-06-20 12:59 UTC, marijarahman commented on src/actions/types.js
> +export const SHIP_GET_DATA = {
it's supposed to be named VESSEL_ACTION_TYPES

2017-06-20 12:59 UTC, marijarahman commented on src/components/FiltersVessel/FiltersVesselFooter.js
> +            <Footer>
You could create a helper for this (something like menu helper)

2017-06-20 13:54 UTC, merged