added saga
marko2606/stena-react-native pull request #6
Opened 2017-06-13 11:32 UTC by NemanjaManot

2017-06-13 13:36 UTC, marijarahman approved these changes

2017-06-14 08:07 UTC, marijarahman requested changes

2017-06-14 08:07 UTC, marijarahman commented on src/components/AlertsNotifications/AlertsNotificationsPicker.js
> +                onSelect={ (index) => console.log(index)} // TODO
remove console.log

2017-06-14 08:07 UTC, marijarahman commented on src/components/AlertsNotifications/AlertsNotificationsPicker.js
> +                textStyle={{ color: colors['grayColor'], padding: 12, fontSize: 13, borderColor: 'red' }}
Can you move this to separate object?

2017-06-14 08:07 UTC, marijarahman commented on src/shared/ModalDropdown/ModalDropdown.js
> +            defaultValue={props.defaultValue}
destructure

2017-06-14 08:07 UTC, marijarahman commented on src/components/AlertsNotifications/AlertsNotificationsPicker.js
> +                dropdownStyle={{ flex: 1, width: '91%', height: '60%', backgroundColor: 'transparent', borderWidth: 0 }}
move to styles object

2017-06-14 08:07 UTC, marijarahman commented on src/components/AlertsNotifications/AlertsNotificationsPicker.js
> +    'MORE OPTIONS',
double more options

2017-06-14 08:16 UTC, marijarahman commented on src/components/AlertsNotifications/AlertsNotificationStyle.js
> +        width: '92%',
why?

2017-06-14 08:19 UTC, marijarahman commented on src/components/AlertsNotifications/AlertsNotificationsPicker.js
> +                onSelect={ (index) => console.log(index)} // TODO
what are you going todo? remove console log :)

2017-06-14 08:21 UTC, marko2606 commented on src/components/AlertsNotifications/alerts-reducer.js
> +            return Object.assign({}, state, {
Why are you not using spread operator?

2017-06-14 08:21 UTC, NemanjaManot commented on src/components/AlertsNotifications/AlertsNotificationStyle.js
> +        width: '92%',
hardcoded. for now...

2017-06-14 08:23 UTC, marko2606 commented on src/sagas/index.js
> +import watchGetData from '../components/AlertsNotifications/alerts-saga';
Why is the name different from the file being imported, and why aren't you using camelCase?

2017-06-14 08:24 UTC, NemanjaManot commented on src/components/AlertsNotifications/AlertsNotificationsPicker.js
> +                dropdownStyle={{ flex: 1, width: '91%', height: '60%', backgroundColor: 'transparent', borderWidth: 0 }}
done

2017-06-14 08:25 UTC, NemanjaManot commented on src/components/AlertsNotifications/AlertsNotificationsPicker.js
> +                textStyle={{ color: colors['grayColor'], padding: 12, fontSize: 13, borderColor: 'red' }}
done

2017-06-14 08:30 UTC, NemanjaManot commented on src/components/AlertsNotifications/alerts-reducer.js
> +            return Object.assign({}, state, {
because Lale told that Object.assign is better solution. :)

2017-06-14 08:39 UTC, NemanjaManot commented on src/sagas/index.js
> +import watchGetData from '../components/AlertsNotifications/alerts-saga';
import name can not have dash

2017-06-14 09:36 UTC, marko2606 approved these changes

2017-06-15 07:45 UTC, merged